: ${AWS_REGION?"Need to set AWS_REGION environment variable"}
: ${PARAMS_YAML?"Need to set PARAMS_YAML environment variable"}

if [ ! $# -eq 1 ]; then
  echo "Must provide workload_name as arg"
  exit 1
fi

WORKLOAD=$1
DEV_NAMESPACE=$(yq e .tap.dev-namespace $PARAMS_YAML)


# Create repository for worklaod images created by TBS
aws ecr create-repository --repository-name tanzu-application-platform/$1-$DEV_NAMESPACE --region $AWS_REGION

# Create repository for workload K8s YAML generated by the supply chain (when using registry-ops)
aws ecr create-repository --repository-name tanzu-application-platform/$1-$DEV_NAMESPACE-bundle --region $AWS_REGION

# Create repository for workload's source code for inner-loop development
aws ecr create-repository --repository-name tanzu-application-platform/$1-$DEV_NAMESPACE-source --region $AWS_REGION
